### ISSUE TITLE
Write tests for forcetorque plugin

### ISSUE THREAD

**Issue by traversaro** [robotology/gz-yarp-plugins#20]
Example for gazebo-classic: https://github.com/robotology/gazebo-yarp-plugins/tree/master/tests .

In general, we need to understand if we want to launch gz-sim as a library, or as an executable .

**Comment by traversaro** [comment]
I found some related material: https://gazebosim.org/api/sim/7/test_fixture.html and https://github.com/gazebosim/gz-sim/tree/main/examples/standalone/gtest_setup . In particular the example shows also how to integrate with googletest, so probably it is a good starting point!

**Comment by lucapa17** [comment]
@traversaro 
For the moment we have done this 5589283ff695e28f0b3903f74e0131533f7abcb1.
We used [gz::sim::TestFixture](https://gazebosim.org/api/sim/7/test_fixture.html). The test simply compares the values coming from the yarp port and the expected values (e.g. forceZ must be equal to -9.8*10).
We don't know if it is a correct idea or if we should consider something else.

**Comment by traversaro** [comment]
Nice start! The test is passing fine on your machines? Can you open a PR so that we can see if the test is passing fine also in the CI? 

Probably a possible improvement is not directly read the port, but read it through the `multipleanalogsensorsclient` device. For an example of how to read the data via the `multipleanalogsensorsclient` , check the code in https://github.com/robotology/yarp/pull/2881#issuecomment-1604132755 (just the first section, the second section will only be usable once that PR is merged and released).
