### ISSUE TITLE
Add coverage test for forcetorque plugin 

### ISSUE THREAD

**Issue by traversaro** [robotology/gz-yarp-plugins#21]

**Comment by GiacomoBisio** [comment]
@traversaro Do you have any advice for the coverage test? Thank you in advance!

**Comment by traversaro** [comment]
I never setup code coverage integration in our projects, but let's try. For example, an example codebase that integrates coverage is https://github.com/temken/template_cpp_cmake_libphysica .

Let's decompose the practice of doing coverage in some steps:
* 0. We just need to add coverage to one CI job, so probably for coverage we can concentrate on the apt job
* 1. To collect coverage data, you need to compile all your code with the `--coverage` flag, and in Debug mode (to avoid that different lines are merged together or re-ordered by the optimizers). Enabling this option ensure that whenever we run the tests, a `.gcno` file is also generated, that contains information on which lines have been tested by the test (see https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Instrumentation-Options.html for more nfo)
* 2. Once you have all the .gcno files, you need something to collect them in a structured form, such as gcov or lcov 
* 3. Then, you need someway to get the files by gcov/lcov and display them. Possible ways to do so are services like codecov (https://about.codecov.io/) or simple github actions like https://github.com/threeal/gcovr-action

Again, I do not have a lot of experience on this, so feel free to explore yourself also in other directions.

**Comment by lucapa17** [comment]
> * 3. Then, you need someway to get the files by gcov/lcov and display them. Possible ways to do so are services like codecov (https://about.codecov.io/) or simple github actions like https://github.com/threeal/gcovr-action

For the moment we decided to use github actions like https://github.com/threeal/gcovr-action because to use other services like codecov (https://about.codecov.io/) we should configure them, but we don't have the required permissions

**Comment by lucapa17** [comment]
> Ok! If you want to test any system just ask and I can add it to the repo.

If possible, we would like to try codecov. Thanks a lot!

**Comment by traversaro** [comment]
> If possible, we would like to try codecov. Thanks a lot!



Ok! I received this instructions:

~~~
Step 1: add repository token as [repository secret](https://github.com/robotology/gz-yarp-plugins/settings/secrets/actions)

Admin required to access repo settings > secrets and variable > actions

CODECOV_TOKEN=<..>

Step 2: add Codecov to your [GitHub Actions workflow yaml file](https://github.com/robotology/gz-yarp-plugins/tree/main/.github/workflows)

After tests run, this will upload your coverage report to Codecov:

- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

After you committed your changes and ran the repo's CI/CD pipeline. In your pull request, you should see two status checks and PR comment.
codecov patch and project

Once merged to the default branch, subsequent pull requests will have checks and report comment. Additionally, you'll find your repo coverage dashboard here.
~~~

I already completed Step 1, can you give me the mail you used to register to codecov so I can add you?

**Comment by traversaro** [comment]
I can't find you, did you try to log in codecov at least once?

**Comment by lucapa17** [comment]
Yes I did

**Comment by traversaro** [comment]
> Yes I did

Ok, now I see you, you should have the access enabled.
